### PR TITLE
Continuous testing ,deployment & documentation.

### PR DESCRIPTION
**Pull request by tartavull**
By merging this pull request you can install by doing:
pip install dataprovider

### CODE REVIEW

**Comment by xiuliren** [comment]
@torms3 how about merging this PR? It is a good time to clean up code

**Comment by tartavull** [comment]
Let me know if you want me to squash commits and rebase to master

**Comment by tartavull** [comment]
Let me know if you want me to squash commits and rebase to master. Probably lots of things changed since when I opened this.

**Comment by xiuliren** [comment]
patchprovider might be a more accurate name?

**Comment by xiuliren** [comment]
@tartavull I have just rebased the code and create a new PR. https://github.com/torms3/DataProvider/pull/8

**Pull request closed without merging**
