### PR TITLE
rebased Ignacio's fork

### PR DESCRIPTION
**Pull request by xiuliren**
merged master and Ignacio's fork and renamed as patchprovider!
@torms3 review this?
@tartavull the travis test do not work.

### CODE REVIEW

**Comment by torms3** [comment]
@jingpengw I'm not using the master branch anymore, I left it intact just because our old pipeline is based on the master and async branches. I'm exclusively using the refactoring branch and it has diverged dramatically from the master. So I don't know what to do with this pull request. Maybe I just need to segregate the refactoring branch to a new repo.

**Comment by tartavull** [comment]
Nobody is using master them right?
Why don't we replace master with refractor?
And if this commits stills add useful functionality we will rebase this branch again from the "new master" (refractor branch)

**Comment by tartavull** [comment]
Also, copying the repo to seung-lab org might make it easier to collaborate (I will make sure Kisuk's name is set as author in the readme)

**Comment by xiuliren** [comment]
yep, moving to seung-lab will make it easier. 
@torms3 create a tag for master as backup and then merge refactored to master?

**Comment by torms3** [comment]
@jingpengw @tartavull I think creating a new seung-lab repo with the refactoring branch should be the easiest. I do appreciate @tartavull's contribution so you're welcome to keep on it once I move to a new repo.

**Pull request closed without merging**
